import mongoose, { Document, Schema } from "mongoose";

export interface IDeliveryItem {
    name: string;
    quantity: number;
    price: number;
    total: number;
    productId?: mongoose.Types.ObjectId;
}

export interface IDeliveryOrder extends Document {
    orderCode: string; // Generated by backend
    buyerId?: mongoose.Types.ObjectId;
    buyerName: string;
    deliveryDate: Date;
    
    // Items
    items: IDeliveryItem[];
    
    // Totals
    amount: number;
    
    // Options
    isInvoice: boolean;
    isDebt: boolean;
    isShipped: boolean;
    
    // Proof
    proofImage?: string;
    
    // Notes
    note?: string;
    
    // Status
    status: "draft" | "completed" | "cancelled";
    
    // Metadata
    createdBy: mongoose.Types.ObjectId;
    createdAt: Date;
    updatedAt: Date;
}

const DeliveryItemSchema = new Schema<IDeliveryItem>({
    name: {
        type: String,
        required: true,
        trim: true
    },
    quantity: {
        type: Number,
        required: true,
        min: [1, "Quantity must be at least 1"]
    },
    price: {
        type: Number,
        required: true,
        min: [0, "Price cannot be negative"]
    },
    total: {
        type: Number,
        required: true,
        min: [0, "Total cannot be negative"]
    },
    productId: {
        type: Schema.Types.ObjectId,
        ref: "Product"
    }
});

const DeliveryOrderSchema = new Schema<IDeliveryOrder>(
    {
        orderCode: {
            type: String,
            required: true,
            unique: true,
            trim: true,
            uppercase: true
        },
        buyerId: {
            type: Schema.Types.ObjectId,
            ref: "Buyer"
        },
        buyerName: {
            type: String,
            required: false, // Optional for draft orders, will be validated in controller
            trim: true,
            default: ""
        },
        deliveryDate: {
            type: Date,
            required: true
        },
        items: [DeliveryItemSchema],
        amount: {
            type: Number,
            required: true,
            min: [0, "Amount cannot be negative"]
        },
        isInvoice: {
            type: Boolean,
            default: false
        },
        isDebt: {
            type: Boolean,
            default: false
        },
        isShipped: {
            type: Boolean,
            default: false
        },
        proofImage: {
            type: String,
            trim: true
        },
        note: {
            type: String,
            trim: true
        },
        status: {
            type: String,
            enum: ["draft", "completed", "cancelled"],
            default: "draft"
        },
        createdBy: {
            type: Schema.Types.ObjectId,
            ref: "User",
            required: true
        }
    },
    {
        timestamps: true,
        toJSON: { virtuals: true },
        toObject: { virtuals: true }
    }
);

// Indexes
DeliveryOrderSchema.index({ orderCode: 1 }, { unique: true });
DeliveryOrderSchema.index({ buyerName: 1 });
DeliveryOrderSchema.index({ deliveryDate: 1 });
DeliveryOrderSchema.index({ createdAt: -1 });
DeliveryOrderSchema.index({ createdBy: 1 });
DeliveryOrderSchema.index({ isShipped: 1 });

// Pre-save middleware to calculate amount
DeliveryOrderSchema.pre("save", function (next) {
    if (this.items && this.items.length > 0) {
        this.amount = this.items.reduce((total, item) => {
            return total + (item.total || item.quantity * item.price);
        }, 0);
    }
    next();
});

export const DeliveryOrder = mongoose.model<IDeliveryOrder>("DeliveryOrder", DeliveryOrderSchema);

